### ISSUE TITLE
Classname::class notation is introduced in PHP 5.5+

### ISSUE THREAD

**Issue by vitrus** [Pierstoval/TranslationBundle#2]
I get the following error: 

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /Applications/XAMPP/xamppfiles/htdocs/symfony.local/www/vendor/pierstoval/translation-bundle/Admin/TranslationAdmin.php on line 41

When running the Translation(Sonata)Admin in PHP 5.4, the Translation::class notation on lines 41 and 44, this notation is used. 5.4 is not that old that it should not be supported anymore or is it?

(The PHP documentation on the ::class notation)
http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by Pierstoval** [comment]
As this notation is not a very big deal and there is no BC break, I don't think it is a problem to switch to the "old" notation :)
